#!/bin/sh

path=$(pwd)

cp $path/background.jpg $HOME/Images

# HOME Directory


# Config directories
[ ! -d $HOME/.config ] && mkdir $HOME/.config

## Users-dirs
ln -sf $path/config/user-dirs.dirs $HOME/.config/user-dirs.conf
ln -sf $path/config/user-dirs.locale $HOME/.config/user-dirs.locale

## Zsh
ln -sf $path/.zshenv $HOME/.zshenv
[ ! -d $HOME/.config/zsh ] && mkdir $HOME/.config/zsh 
ln -sf $path/config/zsh/zshrc $HOME/.config/zsh/.zshrc
ln -sf $path/config/zsh/zprofile $HOME/.config/zsh/.zprofile
ln -sf $path/config/zsh/p10k.zsh $HOME/.config/zsh/.p10k.zsh

## Alacritty
[ ! -d $HOME/.config/alacritty ] && mkdir $HOME/.config/alacritty
ln -sf $path/config/alacritty/alacritty.toml $HOME/.config/alacritty/alacritty.toml

## Bspwm
[ ! -d $HOME/.config/bspwm ] && mkdir $HOME/.config/bspwm
ln -sf $path/config/bspwm/bspwmrc $HOME/.config/bspwm/bspwmrc

## Sxhkd
[ ! -d $HOME/.config/sxhkd ] && mkdir $HOME/.config/sxhkd
ln -sf $path/config/sxhkd/sxhkdrc $HOME/.config/sxhkd/sxhkdrc

## Picom
[ ! -d $HOME/.config/picom ] && mkdir $HOME/.config/picom
ln -sf $path/config/picom/picom.conf $HOME/.config/picom/picom.conf

## X11
[ ! -d $HOME/.config/X11 ] && mkdir $HOME/.config/X11
ln -sf $path/config/X11/.xinitrc $HOME/.config/X11/.xinitrc


