#!/bin/sh

path=$(pwd)

# Home directory
ln -sf $path/.bashrc $HOME/.bashrc
ln -sf $path/.zshrc $HOME/.zshrc

# Config directories
[ ! -d $HOME/.config ] && mkdir $HOME/.config

# Alacritty
[ ! -d $HOME/.config/alacritty ] && mkdir $HOME/.config/alacritty
ln -sf $path/config/alacritty/alacritty.toml $HOME/.config/alacritty/alacritty.toml

# Bspwm
[ ! -d $HOME/.config/bspwm ] && mkdir $HOME/.config/bspwm
ln -sf $path/config/bspwm/bspwmrc $HOME/.config/bspwm/bspwmrc

# Sxhkd
[ ! -d $HOME/.config/sxhkd ] && mkdir $HOME/.config/sxhkd
ln -sf $path/config/sxhkd/sxhkdrc $HOME/.config/sxhkd/sxhkdrc
