#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

picom --config $HOME/.config/picom/picom.conf &
$HOME/.config/polybar/launch.sh &
feh --bg-fill $HOME/Images/1030909-om-wallpaper-1920x1080-for-xiaomi.jpg

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^2' follow=on
bspc rule -a qBittorrent desktop='^10' follow=off
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

