# History in cache directory
HISTSIZE=10000
SAVEHIST=10000
HISTFILE=$XDG_STATE_HOME/zsh/zhistory

# Completion
autoload -U compinit
zstyle ':completion:*' menu select
zmodload zsh/complist
compinit -d $XDG_CACHE_HOME/zsh/zcompdump-$ZSH_VERSION
_comp_options+=(globdots) # With hidden files

# Prompt
fpath=( "$ZDOTDIR/functions" $fpath )
#autoload -U promptinit
#promptinit
#prompt purification
autoload -Uz prompt_purification_setup && prompt_purification_setup
# Vi mode
bindkey -v
export KEYTIMEOUT=1

# Plugins
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh 2>/dev/null
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh 2>/dev/null
source $ZDOTDIR/plugins/archlinux.plugin.zsh 2>/dev/null
source $ZDOTDIR/plugins/git.plugin.zsh 2>/dev/null
